### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by Aqua1ung** [RDFLib/sparqlwrapper#102]
Attempting to query a SPARQL endpoint over HTTPS, not working.

Here's the script, and feel free to give it a try:

from SPARQLWrapper import SPARQLWrapper
queryString = "SELECT * WHERE { ?s ?p ?o. }"
sparql = SPARQLWrapper("https://admin:admin@stardog.eupathdb.org:5820/EuPathOntology/query")
sparql.setQuery(queryString)
try :
   ret = sparql.query()
except :
   deal_with_the_exception()

**Comment by dayures** [comment]
@Aqua1ung I tried with another SPARQL endpoint over https (https://landportal.org/sparql) and it works.

I tried your snippet in Python 2.7 and this error is raised "urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>"

Which version of Python are you using?
Which version of SPARQLWrapper are you using?

**Comment by dayures** [comment]
Thanks for contributing to this issue. As it has been more than 90 days since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!

**Comment by D063520** [comment]
Hi,

I have the same problem when using the wikidata endpoint:

endpoint = "https://query.wikidata.org/sparql"

This should work or?

Merci
D063520
