### ISSUE TITLE
How to query local dataset

### ISSUE THREAD

**Issue by TamouzeAssi** [RDFLib/sparqlwrapper#117]
Hello,

I have a question on how to use sparqlwrapper to qeury a local dataset (e.g my dataset is the folder ./dataset/graph1.rdf)

Thank you

**Comment by dayures** [comment]
SPARQLWrapper is a wrapper for a remote SPARQL endpoint (so a system that provides SPARQL as protocol is needed). As far as your question looks like that a simple dataset (file) is loaded as a graph, SPARQLWrapper is not going to be really helpful.

Maybe you can have a look on this example of rdflib, that would fit more into your idea:
http://rdflib.readthedocs.io/en/stable/intro_to_sparql.html

**Comment by dayures** [comment]
Thanks for contributing to this issue. As it has been more than 90 days since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
