### ISSUE TITLE
Sparql Wrapper not returning the expected results 

### ISSUE THREAD

**Issue by sonilamato** [RDFLib/sparqlwrapper#118]
I am running into an issue that: Firsty when I execute the following Sparql query in the dbpedia sparql online editor I get the expected results, but when I execute the same query with sparql wrapper I dont receive the same results as the online sparql query in dbpedia. The query is :
```
 "PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
          PREFIX prop: <http://dbpedia.org/property/>
    SELECT *
    FROM <http://dbpedia.org/page_links> WHERE {
              <http://dbpedia.org/resource/Albania> ?p  <http://dbpedia.org/resource/Tirana> } limit 3"
```
and the sparqlwrapper code is
```
query = """
        PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
          PREFIX prop: <http://dbpedia.org/property/>
    SELECT *
    FROM <http://dbpedia.org/page_links> WHERE {
              <http://dbpedia.org/resource/Albania> ?p  <http://dbpedia.org/resource/Tirana> } limit 3"""
    print(query)
    sparql = SPARQLWrapper("http://dbpedia.org/sparql")
    sparql.setQuery(query)
    sparql.setReturnFormat(JSON)
    results_list=(sparql.query().convert())
    # print(query)
    print('exist', results_list)
```
How can I get the same results for this issue?

**Comment by dayures** [comment]
![captura](https://user-images.githubusercontent.com/1654811/42084349-b5294124-7b8d-11e8-807b-d9fcafef6c87.PNG)

I think that the issue here is regarding the "Default Data Set Name (Graph IRI)" (with value `http://dbpedia.org`) that it is set in dbpedia SPARQL online editor.

In the case of the dbpedia SPARQL online editor, the query includes the default graph IRI `http://dbpedia.org` (you can look at it as a FROM clause). So, the query is like

```
SELECT *
FROM <http://dbpedia.org> 
FROM <http://dbpedia.org/page_links> 
WHERE {
```

GET request using dbpedia SPARQL online editor
http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=PREFIX+rdfs%3A%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+prop%3A+%3Chttp%3A%2F%2Fdbpedia.org%2Fproperty%2F%3E%0D%0ASELECT+*%0D%0AFROM+%3Chttp%3A%2F%2Fdbpedia.org%2Fpage_links%3E+%0D%0AWHERE+%7B%0D%0A+++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FAlbania%3E+%3Fp++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FTirana%3E+%0D%0A%7D+limit+3&format=application%2Fsparql-results%2Bjson&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on&run=+Run+Query+

But when SPARQLWrapper is used, this FROM clause is not present.

```
SELECT *
FROM <http://dbpedia.org/page_links> 
WHERE {
```
GET request from SPARQLWrapper 
http://dbpedia.org/sparql?query=PREFIX+rdfs%3A%3Chttp%3A//www.w3.org/2000/01/rdf-schema%23%3E%0APREFIX+prop%3A+%3Chttp%3A//dbpedia.org/property/%3E%0ASELECT+%2A%0AFROM+%3Chttp%3A//dbpedia.org/page_links%3E+%0AWHERE+%7B%0A++++%3Chttp%3A//dbpedia.org/resource/Albania%3E+%3Fp++%3Chttp%3A//dbpedia.org/resource/Tirana%3E+%0A%7D+limit+3&output=json&results=json&format=json

So, in order to obtain the same results, you can edit your query in SPARQLWrapper or remove the default graph uri in dbpedia SPARQL online editor.

More information in Virtuoso documentation: http://docs.openlinksw.com/virtuoso/rdfdefaultgraph/

**Comment by dayures** [comment]
Thanks for contributing to this issue. As it has been more than 90 days since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
