### ISSUE TITLE
can we run tests without network access?

### ISSUE THREAD

**Issue by sandrotosi** [RDFLib/sparqlwrapper#146]
Hello,
in Debian we are careful not to allow a build process to access the internet during the package creation. It appears as if every test in sparqlwrapper *does* require network access, which makes the entire test suite to fail :)

is there any way (even if not already implemented) to run the test suite without accessing internet?

Thanks
Sandro

**Comment by dayures** [comment]
Hi @sandrotosi ,

well, I can see 2 options:

- set up in your localhost all this kind of triplestores and query them locally
- or there is a suite of test that don't require internet access: https://github.com/RDFLib/sparqlwrapper/blob/master/test/wrapper_test.py

Is that fine for the Debian package creation ?

**Comment by dayures** [comment]
Thanks for contributing to this issue. As it has been more than 90 days since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
