### ISSUE TITLE
Tarballs at pypi aren't identical to git snapshot... which is suboptimal

### ISSUE THREAD

**Issue by olberger** [RDFLib/sparqlwrapper#23]
Trying to update the Debian package I noticed that the tarball isn't identical at PyPI or here on github.

I personally think it would be better if there wasn't 2 distribution archives.

**Comment by dayures** [comment]
@olberger currently, the tarballs are still not identical (but some steps have been done in order to align them). 

BTW, @wikier what do you think to rename the folder `scripts` to `examples`? After having a look on the debian package, I think that it makes sense. https://packages.debian.org/stretch/all/python-sparqlwrapper/filelist

**Comment by dayures** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
