### ISSUE TITLE
subject literal query doesn't raise exception even though endpoint complains

### ISSUE THREAD

**Issue by joernhees** [RDFLib/sparqlwrapper#96]
### example:

```python
import SPARQLWrapper
sparql = SPARQLWrapper.SPARQLWrapper('http://dbpedia.org/sparql')
sparql.setQuery('''
    SELECT DISTINCT ?target WHERE {
     ?target ?vcb1 "en" .
     "en" ?vcb0 ?target .
    }
''')
sparql.setReturnFormat(SPARQLWrapper.JSON)
print(sparql.queryAndConvert())
```

### output:
```
{u'head': {u'link': [], u'vars': [u'target']},
 u'results': {u'bindings': [], u'distinct': False, u'ordered': True}}
```
This looks as if everything was fine, just nothing matched...

### expected: 
Some sort of exception being raised.

Have a look at what the [endpoint actually returns](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=++++SELECT+DISTINCT+%3Ftarget+WHERE+%7B%0D%0A+++++%3Ftarget+%3Fvcb1+%22en%22+.%0D%0A+++++%22en%22+%3Fvcb0+%3Ftarget+.%0D%0A++++%7D&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on&run=+Run+Query+) in form of a 400:

```
Virtuoso 37000 Error SP031: SPARQL compiler: No one quad map pattern is suitable for GRAPH <http://dbpedia.org> { "en" ?vcb0 ?target } triple at line 5

SPARQL query:

#output-format:text/html
define sql:signal-void-variables 1 define input:default-graph-uri <http://dbpedia.org>     SELECT DISTINCT ?target WHERE {
     ?target ?vcb1 "en" .
     "en" ?vcb0 ?target .
    }
```

**Comment by dayures** [comment]
Actually, the endpoint complaints because the parameters of the queries are slightly different, between Virtuoso SPARQL Query Editor and SPARQLWrapper.

If the parameter `debug` is removed from the URI generated by the Virtuoso SPARQL Query Editor, Virtuoso returns `200 OK`, the same return as SPARQLWrapper because this parameter is not added in the query sent by SPARQLWrapper.

The parameter can be also removed using the UI, unchecking the option "Strict checking of void variables". 

BTW, the parameter debug with value off (`debug=off`), is not working as expected (maybe it works as intended, but I don't know.

**Comment by joernhees** [comment]
oh, nice catch, didn't spot that
